/*
 * This source file was generated by the Gradle 'init' task
 */
package javaprojects;

public class App {

  public static void main(String[] args) {

    Oops oops = new Oops();
    
    int number = oops.getInput(1, 10, "Enter a number from 1 to 10: ", "Invalid Input. Try again: ");
    System.out.println("The value chosen by the user is " + number);
  } 

}